name: Compare functions
on: push
jobs:
    compare:
        runs-on: ubuntu-latest
        steps:
            - run: printenv | grep '_FUNC'
              env:
                CONRAINS_FUNC: ${{contains('Hello','ell')}}
                STARTS_WITH_FUNC: ${{startsWith('Hello','He')}}
                ENDS_WITH_FUNC: ${{endsWith('Hello','lo')}}