name: Hash functions
on: push
jobs:
    hash:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: echo "${PATH}"
            - run: echo "${HASH}"
              env:
                PATH: ${{'.github/workflows/*.yml'}}
                HASH: ${{hashFiles('.github/workflows/*.yml')}}