name: Literals
on: push
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - run: printenv | grep 'LITERAL_'
              env:
                LITERAL_NULL: ${{null}}
                LITERAL_BOOLEAN: ${{true}}
                LITERAL_NUM: ${{1234}}
                LITERAL_STR: ${{'Hello'}}
                LITERAL_OMIT_STR: World
